<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.3.3" />
    <ProjectReference Include="..\..\Dinah.Core\Dinah.Core.csproj" />
    <ProjectReference Include="..\TestCommon\TestCommon.csproj" />
  </ItemGroup>

</Project>
